name: Android CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v6

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
          distribution: 'zulu'
          java-version: '21.0.6' # Runs the build engine on Java 21
          cache: 'gradle'       # Accelerates build speeds

    - name: Run Android Lint
      run: ./gradlew lintDebug

    - name: Upload Lint Report Artifact
      uses: actions/upload-artifact@v6
      if: always() # CRITICAL: Ensures the report uploads even if the lint step fails
      with:
          name: android-lint-report
          path:
            "**/build/reports/lint-results-debug.html"
          retention-days: 7

  unit-test:
    name: Unit Tests
    needs: lint
    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read

    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21.0.6' # Runs the build engine on Java 21
          cache: 'gradle'       # Accelerates build speeds

      - name: Run Unit tests
        run: ./gradlew testDebugUnitTest

      - name: Upload Unit Test Report Artifact
        uses: actions/upload-artifact@v4
        if: always() # CRITICAL: Captures reports even when tests fail
        with:
          name: android-unit-test-report
          path: "**/build/reports/tests/testDebugUnitTest/" # Directs to the HTML test report folder
          retention-days: 7

      #Render results directly in GitHub UI
      - name: Publish Test Report to GitHub
        uses: dorny/test-reporter@v1
        if: always() # Ensures reports are generated even when tests fail!
        with:
          name: Android Unit Test Results
          path: "**/build/test-results/testDebugUnitTest/*.xml" # Points to raw XML files
          reporter: java-junit                                  # Tells the action to look for JUnit format

      - name: Run All Tests & Aggregate Coverage
        run: ./gradlew koverHtmlReport koverXmlReport

      - name: Upload Aggregated Coverage Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-coverage-report
          path: "build/reports/kover/html/"
          retention-days: 7